### ISSUE TITLE
Playback/Render received video/audio streams

### ISSUE THREAD

**Issue by adshrc** [Streampunk/grandiose#1]
Hi,

i was wondering, if there is a (best practice) way to playback the received audio and video streams. We are building an indoor livestream system, which will be NDI based. The idea was, to build a webapp (Angular,...) and use this as dependency to play the stream.

Thanks in advance!

**Comment by sparkpunkd** [comment]
I don't think that grandiose is going to work with a webapp for your use case for two reasons:

* grandiose is a native binding requiring compilation-on-install, a feature not supported by browsers;
* NDI uses multicast DNS (mDNS) for stream and device discovery, a feature not available from the browser.

Grandiose, a prototype, was written to demonstrate access to uncompressed data from NDI streams in server-side Node.JS applications. For a webapp, you probably need to consider using compressed streams?

Good

**Comment by adshrc** [comment]
Thanks for replying.

- sure, but the compilation is done while installing dependencies (npm install). As long as the host machine and the "client" machine are windows x64 it should work
- wouldn't a static ip solve this mDNS issue?

rtsp/rtmp would be an easy solution for this problem, but the delay is inacceptable. We expect a max. delay of 500-700ms, our cameras have "natively" ~3000ms. Maybe an NDI/RTSP hybrid would be the best solution.

Thanks!

**Comment by sparkpunkd** [comment]
If you are using grandiose in a backend server, you are correct that it will install fine and mDNS does work (as well as mDNS ever works - watch out for subnets!). As you say, you can (should?) use static addresses. 

Then my concern is that in a webapp, how are you going to get the uncompressed picture data (RGBA) that grandiose would give you to a browser? Sending uncompressed RGB data is pretty heavy on the network.

RTSP/RTMP is an approach ... you could probably work out a way of using FFmpeg as an NDI to RTMP sender. Another alternative is webRTC. A quick Google search suggest some NDI to webRTC gateways are available.
