### ISSUE TITLE
NDI Receiving

### ISSUE THREAD

**Issue by yyy898** [Streampunk/grandiose#11]
Hi all,
i try to receive an ndi stream to later convert it to jpg images to show on a webpage.
but when i run my code the receiver stays undefined, code and error in attachment
![error 1](https://user-images.githubusercontent.com/479392/89765176-19ed1800-daf6-11ea-9063-bb9a14d6df3d.png)
![error 2](https://user-images.githubusercontent.com/479392/89765188-207b8f80-daf6-11ea-97e6-e21a8b7009fd.png)

**Comment by jensstigaard** [comment]
Hi @yyy898 
Are you are beginner JS programmer? The code is very cluttered even though it does very little. As I read your code, you have no return statement in your main-method, and therefore the then() returns undefined no matter what. 
I see the output shows an error code '4040' which means the receiver or data were not found. You could try to change your code such that the try catch is inside the for loop, meaning that every iteration of fetching of a video frame can fail or succeed, and will not stop running when experiencing an error.
Something like this:
```// Read 10 frames
		for (let x = 0; x < 10; x++) {
			try {
				const videoFrame = await receiver.video(timeout)
				console.log(videoFrame)
			} catch (e) { console.error(e) }
		}```
