### ISSUE TITLE
grandiose.find() does not discover existing streams

### ISSUE THREAD

**Issue by cliqer** [Streampunk/grandiose#17]
Using [rse/grandiose](https://github.com/rse/grandiose) and trying to understand how it works though when I use `grandiose.find()` it does not discover existing streams and throws the below error:
```
Error: In file ../src/grandiose_find.cc on line 53, found error: Did not find any NDI streams in the given wait time of 10000ms.
```
If a new stream is created during the waiting period it is being discovered correctly.
Any solutions?

**Comment by Julusian** [comment]
There is a new class based finder implementation, which should resolve this. 
https://github.com/Streampunk/grandiose/blob/master/index.d.ts#L155-L168

I will publish this to npm when I can, I am still chasing for access
