### ISSUE TITLE
Prebuilds

### ISSUE THREAD

**Issue by hrueger** [Streampunk/grandiose#22]
Hi,
would you be interested in providing prebuilds with the npm package? This would make installation and most importantly cross-compilation way easier.
I really like https://github.com/Julusian/pkg-prebuilds because it's build-system agnostic, easy and uncomplicated.

I could make a PR for that.

**Comment by Julusian** [comment]
I'm already working on this https://github.com/Streampunk/grandiose/tree/feat/ci

**Comment by hrueger** [comment]
Even better 👍

**Comment by Julusian** [comment]
This is merged, so will be usable once I can publish to npm

**Comment by hrueger** [comment]
Sounds good, thanks 👍
