### ISSUE TITLE
Building on Ubuntu 22.04 fails

### ISSUE THREAD

**Issue by 2xAA** [Streampunk/grandiose#23]
Trying to run grandiose on Linux as #3 suggests this should now work.

Steps to reproduce:

```bash
mkdir temp
cd temp
npm init -y
npm i -S github:Streampunk/grandiose#b449f37050064ca23f6c74ce4daa026142c67351
```
(using a commit hash as npm doesn't have the latest code)

Full error output: https://gist.github.com/2xAA/c22b2fa77401d8e89d04d7963079dd34

Looks like there's bad links here:
`npm ERR! /usr/bin/ld: cannot find /home/username/.npm/_cacache/tmp/git-cloneRvcC0i/lib/linux_x64/libndi.so.5: No such file or directory`

**Comment by Julusian** [comment]
This looks to be npm/yarn installing from github being problematic..
npm appears to be simply omitting the symlinks, and yarn includes them but pointing to the wrong path.

I guess that the sensible option is to ditch the symlinks and rename the libndi.so.5.5.2 to libndi.so.5 instead

**Comment by Julusian** [comment]
should be better now

**Comment by 2xAA** [comment]
@Julusian Thanks, building now :)
