### ISSUE TITLE
Not finding streams on MacOS

### ISSUE THREAD

**Issue by lukejdav** [Streampunk/grandiose#26]
grandiose.find() isn't detecting streams on MacOS.

`Error: In file ../src/grandiose_find.cc on line 56, found error: Did not find any NDI streams in the given wait time of 10000ms.
`

Tested on Intel and M1 Mac.
Works on Linux.

**Comment by Julusian** [comment]
There is a new class based finder implementation, which should resolve this. 
https://github.com/Streampunk/grandiose/blob/master/index.d.ts#L155-L168

I will publish this to npm when I can, I am still chasing for access
