### ISSUE TITLE
Receiving data continuously

### ISSUE THREAD

**Issue by dortanes** [Streampunk/grandiose#28]
Hi everybody. Are you planning to implement a function that allows to receive video/audio frames continuously (e.g. in callback)? It would be very good.
I'm currently trying to do this with while(){}, but receiver.data() stops returning any data after two frames for some reason.

**Comment by dortanes** [comment]
One more thing: is there any way to get rid of timeout? For example, in find(). I use this library in Electron, and the whole application crashes when the timeout is over.

**Comment by Julusian** [comment]
> One more thing: is there any way to get rid of timeout? For example, in find(). I use this library in Electron, and the whole application crashes when the timeout is over.

If you install from github you will see a new finder implementation which works better. I am still chasing for npm access, so cannot publish to npm yet
