### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by magdesign** [Streampunk/grandiose#3]
Any chance to get this running under Ubuntu Linux ?

Or at least some hints of what we would have to change to get a proper Linux version of this amazing node.

**Comment by rezonant** [comment]
Grandiose is definitely still in a prototype stage, but there is a fork that appears to be addressing Linux support
https://github.com/daveyijzermans/grandiose/commit/443e13ff9237c2a3401b930c877d961b5d2758f4

Perhaps @daveyijzermans would be willing to bring those changes back to mainline.
I will also be investigating Linux support for this library, but it won't be for awhile as I'm just starting to bring NDI support online in my current app.

**Comment by Julusian** [comment]
Support for linux has been merged in #18
