### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by steveostudios** [Streampunk/grandiose#6]
I know this says only Windows is supported, but I was wondering what is stopping this from being Mac as well. Is it just a matter of including mac libraries, or are there some limitations in Node/macOS?

**Comment by jensstigaard** [comment]
If you look under pull requests, there is a pull request I've made, which includes Mac OS support.
https://github.com/Streampunk/grandiose/pull/4

**Comment by Julusian** [comment]
Support for macos has been merged in #18
