### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by justweb1** [Streampunk/grandiose#8]
Hello, I'm just curious if this project is still alive. Are you still working on it? Are you willing to take on contributors and maintainers, etc?

**Comment by jensstigaard** [comment]
@sparkpunkd ?

**Comment by TimPietrusky** [comment]
@jensstigaard maybe instead of a fork you take over the project so we can open issues to your fork? 🙏

**Comment by mackenly** [comment]
@jensstigaard Does your fork include both the Mac and Linux support?

**Comment by jensstigaard** [comment]
> @jensstigaard Does your fork include both the Mac and Linux support?

Yep

**Comment by Julusian** [comment]
I am taking on some responsibility of maintenance here, just waiting on access to npm.

**Comment by TimPietrusky** [comment]
@Julusian awesome, thank you very much!
